- name: Copy zabbix agent configuration file
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart agent
- name: Start zabbix agent
  service:
    name: zabbix-agent
    state: started
    enabled: true
